### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by sberryman** [MSiam/TFSegmentation#1]
I'm assuming your intention was to leave the folder empty as to not push weights to github. Do you have them hosted anywhere for the public to download?

Update: Should have said thank you for the excellent paper published on arXiv today!
Update 2: I should have been more specific, links to the pre-trained models used in your evaluation.

**Comment by MG2033** [comment]
First of all, thank you for your support. The weights will be uploaded as soon as we finish cleaning up the repo.
