### ISSUE TITLE
inference  problem

### ISSUE THREAD

**Issue by hexiangquan** [MSiam/TFSegmentation#11]
FCN8sShuffleNet  last layer  is upscore  with  deconv stride  8  .this layer is very  time comsuming  .on jetson tx2 .this layer  occupy 180 ms .  any optimization ？

**Comment by hexiangquan** [comment]
last layer deconv  stride is big,that make slow .  how to address  this problem?

**Comment by MSiam** [comment]
If you use the tensorflow optimize_inference tool it will improve the overall performance of the network to run faster. We are working on a version of the code that has optimized inference for all the architecture and will release it. It is initially available in optimize_inference branch you can take a look there.
