### ISSUE TITLE
ERROR Please select a proper data_mode BYE

### ISSUE THREAD

**Issue by ytgcljj** [MSiam/TFSegmentation#12]
i run python3 main.py --load_config=unet_vgg16_test.yaml test Train UNetVGG16 is error 

======================End of Report==========================
   [-] build_model : 8.28218 sec, which is 0.13804 mins, which is 0.00230 hours

Training is initializing itself

Initializing the variables of the model
Initialization finished
   [-] init_model : 3.16336 sec, which is 0.05272 mins, which is 0.00088 hours
Searching for a checkpoint

.. No ckpt, SO First time to train :D ..

   [-] load_model : 0.00013 sec, which is 0.00000 mins, which is 0.00000 hours
ERROR Please select a proper data_mode BYE

**Comment by MSiam** [comment]
You have to change the data_mode inside the config file to 'test'
you also need to change some other things:
 data_dir is pointing to the cityscapes data numpy files
img_height: 512, img_width:1024

generally play around in the config file to ensure its compatible to your data and what u need to do.

**Comment by ytgcljj** [comment]
Yes, I'm already amending.
Training is initializing itself

Initializing the variables of the model
Initialization finished
   [-] init_model : 3.02226 sec, which is 0.05037 mins, which is 0.00084 hours
Searching for a checkpoint

.. No ckpt, SO First time to train :D ..

   [-] load_model : 0.00012 sec, which is 0.00000 mins, which is 0.00000 hours
Loading Testing data..
Test-shape-x -- (500, 512, 1024, 3)
Test-shape-y -- (500, 512, 1024)
Test data is loaded
   [-] load_test_data : 1.86830 sec, which is 0.03114 mins, which is 0.00052 hours
Testing mode will begin NOW..
loading a checkpoint for BEST ONE
ERROR NO best checkpoint found

**Comment by MSiam** [comment]
You need to have a trained network that is already saved if you want to run the test/ inference mode. If you already have the checkpoint saved you can modify in the config file 'exp_dir' to point to the location of the checkpoints. This folder should include:
ckpt_folder/best/best_checkpoint_here

Which is the format that its saved with when you run our training.
