### ISSUE TITLE
Question about input image data format

### ISSUE THREAD

**Issue by msson** [MSiam/TFSegmentation#13]
Hello,

First of all, your work is very impressive and helpful. Thank you!

I intend to visualize segmented output image (.png) using my own .png format image on fcn8s_mobilenet model.
And I already trained fcn8s_mobilenet model with cityscape dataset (X_train.npy, Y_train.npy is it right?)

The question is :
1. I would like to know how you make X_val.npy and Y_val.npy using png images so that I simply replace my own data format from png to npy. (Please explain about X_val.npy, Y_val.npy)
2. If I convert my own png image to X_val.npy and Y_val.npy successfully, then the test code will be worked without error? Or should I change some part of your code? (resolution or something else)

Thank you.

--------------------------------------------------------------------------------------------------------------------------------
Here is my result below when Ive converted only one png(1024x512) image to npy file and replaced the file name to X_val.npy in data/full_cityscapes_res/ and run it using the test command (python3 main.py --load_config=fcn8s_mobilenet_test.yaml test Train FCN8sMobileNet)
![image123](https://user-images.githubusercontent.com/35793913/38976072-0d08af04-43eb-11e8-8e4d-c18722677634.png)

**Comment by MSiam** [comment]
Thanks! If you change X_val.npy and Y_val.npy and ensure it has the same size like in your config file for the test it should work.

**Comment by msson** [comment]
Thanks.
