### ISSUE TITLE
Have anyone tried to test with different resolution of input image?

### ISSUE THREAD

**Issue by msson** [MSiam/TFSegmentation#14]
I am trying to test the model with 768*1024 images but it seems not that simple for me.
(I already converted my own images (768*1024) to X_val.npy file.)
Please give me an advice which part of the code I need to modify.
Thanks.

**Comment by msson** [comment]
Also, is it possible to change the number of classes from 20 to less number for training my own input dataset. If possible, please give me some advice which part I have to modify. Thank you.

**Comment by MSiam** [comment]
For changing the number of classes, you should just change num_classes in the config file of the training. and ensure that weights.npy that you have computed for the weighted loss has a numpy array of size (num_classes,). For using different input images change img_width and height in config as well. I just added a change for the master branch as we had it working on another branch. Check now and let us know if there is any other issues.

**Comment by wzhouuu** [comment]
Hi, just wondering how long it would take to train a model from scratch? Let's say if i have ~10,000 640x360 images for training? Thanks for any help!

**Comment by msson** [comment]
Thank you for your reply. I have one more question. Which part do I have to modify if I would like to change input labeled pixel value from road=0~unlabled=19 to different gray colors or 3-dim colors?

**Comment by zeroAska** [comment]
Hi @msson, just wondering which script in `data/` did you use convert your own data to another resolution, `preprocess_cityscapes.py`?

**Comment by YanZhiyuan0918** [comment]
@msson  Hi, could you please tell me what does the file "weight.npy" do? Thanks!
