### ISSUE TITLE
shufflenet_weights.pkl is missing from pretrained_weights package

### ISSUE THREAD

**Issue by huangyuyao** [MSiam/TFSegmentation#15]
Following the instruction in `README.md`, I download `pretrained_weights.zip` from the google drive.
However, it seems that shufflenet_weights.pkl , which is referenced by `config/experiments_config/unet_shufflenet_train.yaml`, is missing from the zip package. Is it correcly packed and uploaded?

I found it a duplicated issue, so close it.

**Comment by MSiam** [comment]
Shufflenet Weights is included now in the pretrained weights, and the final skipnet mobilenet and skipnet shufflenet trained on cityscapes is uploaded as well.
