### ISSUE TITLE
"loss : nan-" error issue

### ISSUE THREAD

**Issue by msson** [MSiam/TFSegmentation#16]
![112233](https://user-images.githubusercontent.com/35793913/39502741-e1f7cb44-4dfc-11e8-862e-83439023d905.png)
When I train the model with my own X_train.npy, Y_train.npy also I made Weights.npy and mean.npy using compute_weights.py file, there is no error but I see loss : nan-.
Ive checked the loss list values and every loss value shows nan.
(My dataset is 1024X768 and labeled 19 classes)

**Comment by harsh-agar** [comment]
Hi @msson, 
I'm facing the same problem on my dataset with 2 classes. 
How did you solve it?
