### ISSUE TITLE
shufflenet_weights

### ISSUE THREAD

**Issue by SiggiKatzlevski** [MSiam/TFSegmentation#17]
Hello everyone. 
Your work looks really interesting so i downloaded everything to try i out. Unfortunetaly there are no pretrained weights for  your shufflenet. Will you publish them at any time?
Regards!

edit: at the moment i only have a jetson tx2 avaible , so train it by my self would be a little tricky because of some lacking ressources, right?

**Comment by MSiam** [comment]
Yes we will publish the Shufflenet pretrained weights and the model trained on cityscapes by end of June. We are finalizing some experiments then we will publish all.

Thanks for your patience
