### ISSUE TITLE
A problem between RTSEG and SHUFFLRSEG

### ISSUE THREAD

**Issue by JipengWuxmu** [MSiam/TFSegmentation#18]
What‘s the differences between RTSEG and SHUFFLRSEG? Those papers used the same methods and code.

**Comment by MSiam** [comment]
RTSeg paper is about the decoupling and evaluation of different architectures. While ShuffleSeg is about utilizing grouped convolution and channel shuffling in semantic segmentation :). I hope you realize its not an issue in the code so I will close and you can inquire on our emails on any further misunderstandings.
