### ISSUE TITLE
MoblienetV2 deeplab v3+

### ISSUE THREAD

**Issue by bhack** [MSiam/TFSegmentation#2]
Do you plan to cover also this new model? Seems that it will arrive in the next PR. Check https://github.com/tensorflow/models/blob/master/research/deeplab/README.md

**Comment by MG2033** [comment]
We'll think about it in the next few days. Thank you.

**Comment by bhack** [comment]
Will be released upstream

**Comment by bhack** [comment]
Check https://github.com/tensorflow/tensorflow/issues/16452#issuecomment-372482314

**Comment by MG2033** [comment]
Thank you very much for that.

**Comment by bhack** [comment]
Merged in https://github.com/tensorflow/models/pull/3709
