### ISSUE TITLE
training code example

### ISSUE THREAD

**Issue by deeptf** [MSiam/TFSegmentation#25]
Hello, Thanks a ton for the code. However do you have pointers on how to run training on new dataset ? Any quick README would be of great help.

**Comment by feitiandemiaomi** [comment]
@MSiam Hi, Thanks for you repo,  It's amazing.  would you like to provide  testing on single?  If I want to test on single image，can you give any advice

**Comment by moemen95** [comment]
hello @feitiandemiaomi ,

You can create a new mode in the train.py and a new function generator with a new data mode .. to just feed forward on a single image.

I can help you to implement it . if you want.

**Comment by TomHJ** [comment]
> Hello, Thanks a ton for the code. However do you have pointers on how to run training on new dataset ? Any quick README would be of great help.

@deeptf  Do you know how to run training on new data set now? I have the same question now. I have images(8-bit color RGB png) and their label images(8-bit gray scale png), but i am not clear how to do next. Does the images' format and label images' format OK to proceed or need to change?  which python script need to be used to process these images?
