### ISSUE TITLE
Install Tensorflow on Jetson TX2

### ISSUE THREAD

**Issue by muthiyanbhushan** [MSiam/TFSegmentation#28]
Hello,

Can you point me on how to install Tensorflow on Jetson TX2 board?

Every help will be appreciated.

Thank you.

**Comment by moemen95** [comment]
I will leave some links.

But mainly you need to understand that the pack of cuda and Cudnn is already installed on jetson TX2.
And the wheel of tensorflow is compiled for jetson.

Here some links:
https://nvidia.app.box.com/v/TF180-Py35-wTRT
https://devtalk.nvidia.com/default/topic/1031300/tensorflow-1-7-wheel-with-jetpack-3-2-/
https://github.com/openzeka/Tensorflow-for-Jetson-TX2
