### ISSUE TITLE
Questions about input image data format

### ISSUE THREAD

**Issue by MMY1994** [MSiam/TFSegmentation#30]
Hello, 
First of all, thank you for your work. 
I am a beginer. I want to use my own .png format image to test or val. So i have some questions.

1.when i run it using the test command  (python3 main.py --load_config=fcn8s_shufflenet_test.yaml test Train FCN8sShufflenet)  have this question.

File "/home/mamingyu/TFSegmentation-master/train/train.py", line 741, in test
    y_batch = self.test_data['Y'][idx:idx + 1]
KeyError: 'Y'

I found the fuction load_test_data in train.py line 389.  The dict self.test_data did not load 'Y'. 

2. Is  X_train.npy corresponding to the train RGB image and Y_train.npy corresponding to the train label image?  How to make a lot of png images become X_val.npy and Y_val.npy so that I simply replace my own data format from png to npy.

3. TFSegmentation/data/ has preprocess_cityscapes_tfrecords.py and preprocess_cityscapes.py .  Is the first .py make png image become TFrecord format and the second .py make png image become npy format? So can i use TFrecord format as my input image data format and how to do that.

Please give me some suggestion. Thank you very much

**Comment by moemen95** [comment]
Thanks ,

1 - I will fix this.

2- You can use the preparing scripts in data folder to convert your png files to npys files.

3- yes exactly .. but it is better to make png image become npy as it is fully working and tested and easier to prepare.

if you wanna any help yo prepare your data.. tell me

**Comment by MMY1994** [comment]
@moemen95 thank you for your help ! And i have another question. when i run the following example command:
python3 main.py --load_config=fcn8s_shufflenet_test.yaml test Train FCN8sShuffleNet 

It give me a FileNotFoundError.  Cannot find X_test.npy , xnames_test.npy and ynames_test.npy

So i checked the "full_cityscapes_res"folder that i download from the Google Drive. i found there is not these three files. 

Do i need to make them ? And test dataset doesn't have labels. why have the ynames_test.npy in the code.

Thank you for your assistance !
