### ISSUE TITLE
Training data and val data size error

### ISSUE THREAD

**Issue by klnsz** [MSiam/TFSegmentation#31]
Hi. Firstly, thank you for this amazing project. 
When I run this code: 
`python3 main.py --load_config=fcn8s_shufflenet_train.yaml train Train FCN8sShuffleNet`
I got an error saying that validation data image size and training data image size is not equal. One of them is 512x1024 while other one is 256x512. I just simply resized whole data and save them. I fixed this issue but I just want to check if there is anyone facing this problem. If so, you should consider to edit the Y_val.npy and X_val.npy file.
If this issue is only the case for me then what could be the reason? 
Thank you.

**Comment by moemen95** [comment]
Thank you klnsz.. We will try to fix this.. but the validation data of 256x512 was for benchmarking the FPS speed.
