### ISSUE TITLE
full_cityscapes_res.zip

### ISSUE THREAD

**Issue by yyfyan** [MSiam/TFSegmentation#32]
good job,
what's the big about the file,I download it ,but failure. I have original cityscape dataset, how convert it to full_cityscapes_res?

**Comment by moemen95** [comment]
In our data folder .. you will find all the kind of preparing the data there.
But mainly you can focus on 
https://github.com/MSiam/TFSegmentation/blob/master/data/preprocess_cityscapes.py
&
https://github.com/MSiam/TFSegmentation/blob/master/data/preprocess_cityscapes_h5.py
