### ISSUE TITLE
I get "Loss:nan-" when training

### ISSUE THREAD

**Issue by harsh-agar** [MSiam/TFSegmentation#33]
Hi,
I'm trying to train on my custom dataset with just two classes (person and none).
I've generated the X_train, Y_train, weights and mean files.
But while training I continuously see 

> loss: nan

My dataset is 512x640 images.

**Comment by MMY1994** [comment]
Hi!
I have same problem when I train it on my dataset(My dataset is 512X1024 and labeled 2 classes)
Could you give me some suggestion please?
