### ISSUE TITLE
Unable to optimize graph using NCHW

### ISSUE THREAD

**Issue by harsh-agar** [MSiam/TFSegmentation#35]
Hi @MSiam,

I'm trying to optimize the graph using the nchw_optimize_inference branch, but after I freeze the graph it is removing the input layer ['network/input/Placeholder'].

This is why optimize_for_inference throws an error
 **KeyError: "The following input nodes were not found: set(['network/input/Placeholder'])\n"**
I also checked the frozen graph on TensorBoard and this node was absent there.

I'm using TensorFlow v1.4

How were you able to generate the frozen model for inference?

Thanks!

**Comment by harsh-agar** [comment]
Hi @MSiam,

It works fine when I use the script optimize_inrference branch  and gives a speed boost of around 8 FPS, but the above error occurs when using nchw_optimize_inference branch.

Thanks!

**Comment by moemen95** [comment]
Hello harsh-agar .. How can i help you

**Comment by harsh-agar** [comment]
Hi @moemen95 

I'm getting a low FPS of around 60 FPS.

When I try to run NCHW optimization, I'm unable to run the optimize_for_inference script as it throws an error that the input layer is not present in the graph (after freezing the graph).

Any suggestions for the same.

Also, did you try to run the model using TensorRT for further optimizations? 

Thanks!

**Comment by MSiam** [comment]
Can you try this optimized_graph on optimize_inference branch try python infer_optimize.py --graph graph_optimized.pb, and let me know what is the framerate you are getting? This is still without NCHW optimization. I am just wondering why you had 7 fps more with the optimization only.
[Optimized_graph](https://drive.google.com/open?id=1-7mrhpkcvZFWHDXIjm2cOIWCbXY60EPR).

**Comment by harsh-agar** [comment]
I trained my own model and now I get around 95-100 FPS. When tested using infer_optimize.py on optimized_graph. Can you suggest some other modifications for further speed boost-up.

Also did you try to run it using TensorRT for FP16 mode. I'm getting stuck at Slice op present in Grouped Convolution. Any suggestion/solution for the same?

**Comment by moemen95** [comment]
No we didn't try using tensorRT .. But it is in our TODO list.. we will try it and let you know..
Please can you tell me your version of CUDA & CUDNN ?!
