### ISSUE TITLE
How to calculate the metrics?

### ISSUE THREAD

**Issue by fanser** [MSiam/TFSegmentation#36]
Thanks for your contribution in this work!
I have seen the metrics scripts in your project. However, are there some publicly evaluation tools for the fair comparison? If not, can I use your scripts to evaluate my model?
thanks ~

**Comment by MSiam** [comment]
You should be able to use the public cityscapes eval script here: 
https://github.com/mcordts/cityscapesScripts/tree/master/cityscapesscripts
Just use data_mode: test_mode in ur config file to get the format needed for the eval script.

**Comment by fanser** [comment]
thanks!
