### ISSUE TITLE
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by msson** [MSiam/TFSegmentation#39]
I got this error code and I know why this error came up because my system environment has CUDA 9.0 CUDNN 7.0 version.

I would like to know how to run this code on my system (My situation is NOT possible to change CUDA version from 9.0 to 8.0).

I think I should change my tensorflow version to run on CUDA 9.0 environment but I do not know how to make it.

Please give me any advice. Thank you.

**Comment by moemen95** [comment]
Hello @msson,

You can install Cuda 9.0 and CUDNN 7.0 and then using pip install tensorflow 1.5
check with nvcc -v 
to check the cuda version working right now.
and you will know which version of cuda is working with tensorflow

**Comment by msson** [comment]
@moemen95 Thanks.
