### ISSUE TITLE
Does anyone know how to start training the model from the best checkpoint?

### ISSUE THREAD

**Issue by msson** [MSiam/TFSegmentation#41]
When I run training codes, it seems not call best checkpoint file and just start from the initial value.

Which part of the codes do I should modify?

**Comment by moemen95** [comment]
There is a base class of train which contains function load_best_model
https://github.com/MSiam/TFSegmentation/blob/master/train/basic_train.py

Check it please.
You can put it in the last lines of the constructor or the first lines of the training code

**Comment by msson** [comment]
@moemen95  Thank you.
