### ISSUE TITLE
How to run with webcam in real time ?

### ISSUE THREAD

**Issue by sfdn123** [MSiam/TFSegmentation#42]
Hi.
I'm really interested in Real-time Semantic Segmentation. So, I'd like to check the latency and accuracy with webcam in real time. Can I check this with this program? and i want to know how to do.
Thanks.

**Comment by moemen95** [comment]
https://github.com/qdraw/tensorflow-object-detection-tutorial/blob/master/test/webcam-show.py
https://towardsdatascience.com/building-a-real-time-object-recognition-app-with-tensorflow-and-opencv-b7a2b4ebdc32


You can integrate OPENCV with python along with our framework and test on a webcam
