### ISSUE TITLE
shape of output data 

### ISSUE THREAD

**Issue by sfdn123** [MSiam/TFSegmentation#43]
Hi.
I ran infer_optimized.py with my webcam by reference to [#20](https://github.com/MSiam/TFSegmentation/issues/20) and [#42](https://github.com/MSiam/TFSegmentation/issues/42#event-1809156935)
But, i cant understand why out.shape = (1, 360, 640) (line38 : out = sess.run(y, feed_dict={x: img}).
i think this should be(360, 640, 3) because this is RGB image.
Can anyone explain this reason?

**Comment by sfdn123** [comment]
Hi.
After that, I understood (1, 360, 640) is Argmax. So, i used img_utils.py to show webcam images. But, fps drop to 80fps→12fps by showing images. im using gtx1080. Can i get more fps ? Thanks.

**Comment by sfdn123** [comment]
Hi. 
After that, I understood (1, 360, 640) is Argmax. So, i used img_utils.py to show webcam images. But, fps drop to 80fps→12fps by showing images. im using gtx1080. Can i get more fps ? 
Thanks.

**Comment by moemen95** [comment]
the code which converts the argmax to an rgb image is very slow and not optimized as it is for looping on values and convert it to the correspond RGB color.

I don't know for now if there is a better algo or implementation for this.
I will try to get you something faster.
if i found something. i will let you know.

**Comment by sfdn123** [comment]
Hi@moemen95
Thank you for your reply. 
I understand, I am looking forward to it.
