### ISSUE TITLE
ValueError: Cannot feed value of shape (8, 512, 1024, 3) for Tensor 'network/input/Placeholder:0', which has shape '(8, 256, 512, 3)'

### ISSUE THREAD

**Issue by sounansu** [MSiam/TFSegmentation#44]
Hi!

I tried to train by command run.sh.
($ python3 main.py --load_config=fcn8s_shufflenet_train.yaml train Train FCN8sShuffleNet)
I encount error as below.

> $ ./run.sh
> /home/sounansu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> 
> Parsing Arguments..
> 
> Using this arguments check it
> 
> batch_size -- 8 --
> batchnorm_enabled -- True --
> bias -- 0.0 --
> config_path -- fcn8s_shufflenet_train.yaml --
> data_dir -- full_cityscapes_res --
> data_mode -- experiment --
> exp_dir -- fcn8s_shufflenet --
> freeze_encoder -- False --
> img_height -- 256 --
> img_width -- 512 --
> learning_decay -- 1e-07 --
> learning_decay_every -- 100 --
> learning_rate -- 0.0001 --
> max_to_keep -- 1 --
> mode -- train --
> model -- FCN8sShuffleNet --
> momentum -- 0.9 --
> num_channels -- 3 --
> num_classes -- 20 --
> num_epochs -- 200 --
> num_groups -- 3 --
> operator -- Train --
> out_dir -- fcn8s_shufflenet --
> pretrained_path -- pretrained_weights/shufflenet_weights.pkl --
> random_cropping -- False --
> save_every -- 10 --
> shuffle -- True --
> test_every -- 10 --
> verbose -- False --
> weight_decay -- 0.0005 --
> weighted_loss -- True --
> 
> 
> 
> Agent is running now...
> 
> 
> 2018-09-07 12:35:22.150963: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
> 2018-09-07 12:35:22.150994: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
> 2018-09-07 12:35:22.355806: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2018-09-07 12:35:22.356259: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
> name: GeForce GTX 1080 Ti
> major: 6 minor: 1 memoryClockRate (GHz) 1.6705
> pciBusID 0000:03:00.0
> Total memory: 10.91GiB
> Free memory: 10.19GiB
> 2018-09-07 12:35:22.356285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0
> 2018-09-07 12:35:22.356295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y
> 2018-09-07 12:35:22.356308: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0)
> 
> Building the MODEL...
> Building the ShuffleNet..
> Layer_name: network/shufflenet_encoder/conv1/Relu -Output_Shape: [8, 127, 255, 24]
> Layer_name: network/shufflenet_encoder/max_pool -Output_Shape: [8, 63, 127, 24]
> Layer_name: network/shufflenet_encoder/stage2_3/Relu -Output_Shape: [8, 32, 64, 240]
> Layer_name: network/shufflenet_encoder/stage3_7/Relu -Output_Shape: [8, 16, 32, 480]
> Layer_name: network/shufflenet_encoder/stage4_3/Relu -Output_Shape: [8, 8, 16, 960]
> 
> Encoder ShuffleNet is built successfully
> 
> 
> The Model is built successfully
> 
>    [-] build_model : 19.11881 sec, which is 0.31865 mins, which is 0.00531 hours
> 
> Training is initializing itself
> 
> Initializing the variables of the model
> Initialization finished
>    [-] init_model : 3.71544 sec, which is 0.06192 mins, which is 0.00103 hours
> Loading ImageNet pretrained weights...
> ImageNet Pretrained Weights Loaded Initially
> 
> 
> Pretrained weights of the encoder is loaded
> Searching for a checkpoint
> 
> .. No ckpt, SO First time to train :D ..
> 
>    [-] load_model : 4.51711 sec, which is 0.07529 mins, which is 0.00125 hours
> Loading Training data..
> Train-shape-x -- (2975, 256, 512, 3) 2975
> Train-shape-y -- (2975, 256, 512)
> Num of iterations on training data in one epoch -- 372
> Training data is loaded
> Loading Validation data..
> Val-shape-x -- (500, 512, 1024, 3) 496
> Val-shape-y -- (500, 512, 1024)
> Num of iterations on validation data in one epoch -- 62
> Validation data is loaded
>    [-] load_train_data : 22.91540 sec, which is 0.38192 mins, which is 0.00637 hours
> Training mode will begin NOW ..
> epoch-0-: 100%|????????????????????????????????????????????????????????????????????????????| 371/372 [01:31<00:00,  4.58it/s]
> epoch-0-loss:14.767903- acc:0.6199
> saving a checkpoint
> Saved a checkpoint
> Validation at step:372 at epoch:1 ..
> Val-epoch-1-:   0%|                                                                                   | 0/62 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "main.py", line 19, in <module>
>     main()
>   File "main.py", line 15, in main
>     agent.run()
>   File "/home/sounansu/anaconda3/TFSegmentation/utils/misc.py", line 18, in timed
>     result = f(*args, **kwargs)
>   File "/home/sounansu/anaconda3/TFSegmentation/agent.py", line 96, in run
>     self.train()
>   File "/home/sounansu/anaconda3/TFSegmentation/agent.py", line 139, in train
>     self.operator.train()
>   File "/home/sounansu/anaconda3/TFSegmentation/train/train.py", line 583, in train
>     epoch=self.model.global_epoch_tensor.eval(self.sess))
>   File "/home/sounansu/anaconda3/TFSegmentation/train/train.py", line 636, in test_per_epoch
>     feed_dict=feed_dict)
>   File "/home/sounansu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
>     run_metadata_ptr)
>   File "/home/sounansu/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
>     % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
> ValueError: Cannot feed value of shape (8, 512, 1024, 3) for Tensor 'network/input/Placeholder:0', which has shape '(8, 256, 512, 3)'

What happened?

**Comment by moemen95** [comment]
Train-shape-x -- (2975, 256, 512, 3) 2975
Train-shape-y -- (2975, 256, 512)
Num of iterations on training data in one epoch -- 372
Training data is loaded
Loading Validation data..
Val-shape-x -- (500, 512, 1024, 3) 496
Val-shape-y -- (500, 512, 1024)

You can see here VALIDATION DATA & TRAINING DATA are not consistent !!!.
Please check them.

**Comment by sounansu** [comment]
I check npy data.
--------------------------------------------------------
 val_data=np.load("data/full_cityscapes_res/X_train.npy")
 val_data.shape
(2975, 512, 1024, 3)
 val_data=np.load("data/full_cityscapes_res/X_val.npy")
 val_data.shape
(500, 512, 1024, 3)
 val_data=np.load("data/full_cityscapes_res/Y_train.npy")
 val_data.shape
(2975, 512, 1024)
 val_data=np.load("data/full_cityscapes_res/Y_val.npy")
 val_data.shape
(500, 512, 1024)'
-------------------------------------------------------------------
train and val shape are same.
But [resized](https://github.com/MSiam/TFSegmentation/blob/52f268523daed3f650dc21538e97f159f10c019c/train/train.py#L294) at train.py by [fcn8s_shufflenet_train.yaml](https://github.com/MSiam/TFSegmentation/blob/52f268523daed3f650dc21538e97f159f10c019c/config/experiments_config/fcn8s_vgg16_train.yaml#L6)   img_hight,img_width parameters.

So, I chang img_hight and img_width parameter

`img_height:   256`
`img_width:    512`

to
`img_height:   512`
`img_width:    1024`

Is this correct?

**Comment by moemen95** [comment]
Yes i think this is correct you shoud make sure that the numpys has the same size(train & val)
And it will be correct.
keep me updated

**Comment by moemen95** [comment]
I believe that X_test .. I was using it for bench-marking and testing the Inference time.
You can load it or change it with whatever you want.

**Comment by sounansu** [comment]
moemen95 
Could you push your X_test.npy to github?

**Comment by moemen95** [comment]
OK i will do that as soon as possible

**Comment by andsnes** [comment]
@moemen95 Hello. Where is 'X_test.npy' file? I can't find it.
