### ISSUE TITLE
convert coco annotation data

### ISSUE THREAD

**Issue by sfdn123** [MSiam/TFSegmentation#46]
Hi.
I want to try training model with my own coco format annotation data. 
So, i have to convert my data into cityscapes format.
I think i can do the work with this directory(TFSegmentation-optimize_inference//data//coco).
Could you tell me how to do it ?
Thanks!

**Comment by moemen95** [comment]
you just need to build numpy arrays with shapes configured in the code and the configurations.
Check load_data functions in train CLASS.

**Comment by sfdn123** [comment]
Now i understand. Thank you for your reply.
