### ISSUE TITLE
Question about your paper

### ISSUE THREAD

**Issue by lxtGH** [MSiam/TFSegmentation#5]
Hello !!!
In your paper "SHUFFLESEG: REAL-TIME SEMANTIC SEGMENTATION NETWORK", **what does the feed layer do? ?  so the upsample methods can be very different according to decoder ?**

**Comment by MG2033** [comment]
The feed layer is just the conventional name used in FCN. It's used to be the input to the class score layer in the SkipNet model.

**Comment by lxtGH** [comment]
Ok, I think too much, thanks for your reply!
