### ISSUE TITLE
Question about the constant hyper-parameter c in class weight

### ISSUE THREAD

**Issue by mrluin** [MSiam/TFSegmentation#62]
Hi,
When I read the paper, I have a question about the constant hyper-parameter c in the weighted cross_entropy, why set value c 1.02, is there something significant?
Thank you.

**Comment by moemen95** [comment]
Hello Mrluin We got this hyper parameter from ENET Paper.

**Comment by mrluin** [comment]
> Hello Mrluin We got this hyper parameter from ENET Paper.

Thank you
