### ISSUE TITLE
Interface or demo for visualization

### ISSUE THREAD

**Issue by baoruxiao** [MSiam/TFSegmentation#7]
Would you be able to provide a simple demo or interface for easy visualize your segmentation performance?

Thanks

**Comment by Archon512** [comment]
I agree the mIOUs and the inference time are good metrics but no images are saved in the output folders. Am I doing something wrong or does the test and inference mode not save anything?

Thanks

**Comment by MG2033** [comment]
I think you're doing something wrong. To save images, you should run the following example command:
python main.py --load_config=fcn8s_shufflenet_test.yaml test Train FCN8sShuffleNet

You have to make sure that out_dir is specified correctly in the config file. Then, you'll find the output images in the directory out/[your_output_dir].

**Comment by Archon512** [comment]
@MG2033 Thanks for the reply, I just retrained and ran the test for the same network with admin rights turns out and it fixed the issue for me

**Comment by MG2033** [comment]
You're welcome. If there are any more issues, feel free to ask us.

**Comment by baoruxiao** [comment]
@MG2033 Thanks, I will try it out.
