### ISSUE TITLE
shufflenet_weights.pkl

### ISSUE THREAD

**Issue by hexiangquan** [MSiam/TFSegmentation#8]
can you share shufflenet_weights.pkl ?

**Comment by MG2033** [comment]
Soon, we'll upload the remaining models. Stay tuned for the updates.

**Comment by futureisatyourhand** [comment]
> Soon, we'll upload the remaining models. Stay tuned for the updates.

Excuse me, where is the shufflenet_weights.pkl file? 
Thanks!!
